(function(a,d,v){function m(a){for(var b={},c,k,q=0;q<a.length;q++)k=a[q],c=k.r+k.s+k.m,k.c&&(b[c]||(b[c]=[]),b[c].push(a[q]));return b}function r(a){for(var b=1;b<arguments.length;b++){var c=arguments[b];try{if(c.isSupported)return c.send(a)}catch(k){}}}function g(){for(var a=0;a<B.length;a++)B[a]();E.length&&r(m(E.splice(0,E.length)),O,L,I);y=M=0}function l(c,J,p){p=p||{};0===p.bf&&b.isBF||(c={r:p.r||b.rid,s:p.s||a.ue_sid,m:p.m||a.ue_mid,mkt:p.mkt||a.ue_mkt,sn:p.sn||a.ue_sn,c:J,d:c,t:p.t||b.d(),
cs:p.c&&a.ue_qsl},p.b?r(m([c]),O,I):p.nb?r(m([c]),O,L,I):p.img||G[J]?r(m([c]),I):p.ff?(E.push(c),g()):p.n?(E.push(c),0===N?g():y||(y=d.setTimeout(g,N))):(E.push(c),M||(M=d.setTimeout(g,H))))}function t(a,b,c){K++;K==x?l({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr"):K<x&&l(a,b,c)}function n(){if(!A){for(var a=0;a<f.length;a++)f[a]();for(a=0;a<B.length;a++)B[a]();r(m(E.splice(0,E.length)),O,I);A=!0}}var h={};(function(){function a(b){return 10>
b?"0"+b:b}function b(a){k.lastIndex=0;return k.test(a)?'"'+a.replace(k,function(a){var b=C[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,k){var u,C,h,e,w=q,g,D=k[a];D&&"object"===typeof D&&"function"===typeof D.toJSON&&(D=D.toJSON(a));"function"===typeof d&&(D=d.call(k,a,D));switch(typeof D){case "string":return b(D);case "number":return isFinite(D)?String(D):"null";case "boolean":case "null":return String(D);case "object":if(!D)return"null";
q+=f;g=[];if("[object Array]"===Object.prototype.toString.apply(D)){e=D.length;for(u=0;u<e;u+=1)g[u]=c(u,D)||"null";h=0===g.length?"[]":q?"[\n"+q+g.join(",\n"+q)+"\n"+w+"]":"["+g.join(",")+"]";q=w;return h}if(d&&"object"===typeof d)for(e=d.length,u=0;u<e;u+=1)"string"===typeof d[u]&&(C=d[u],(h=c(C,D))&&g.push(b(C)+(q?": ":":")+h));else for(C in D)Object.prototype.hasOwnProperty.call(D,C)&&(h=c(C,D))&&g.push(b(C)+(q?": ":":")+h);h=0===g.length?"{}":q?"{\n"+q+g.join(",\n"+q)+"\n"+w+"}":"{"+g.join(",")+
"}";q=w;return h}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var k=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
q,f,C={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},d;"function"!==typeof h.stringify&&(h.stringify=function(a,b,k){var u;f=q="";if("number"===typeof k)for(u=0;u<k;u+=1)f+=" ";else"string"===typeof k&&(f=k);if((d=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})})})();var e=function(){function a(b,c){if(null==b)return c.push("!n");if("number"===typeof b)return c.push("!"+b);if("string"===
typeof b)return"\\"==b[b.length-1]?c.push("'"+b.replace(/'/g,"\\'")+"u005C'"):c.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return c.push(b?"!t":"!f");if(b instanceof Array){c.push("*");for(var k=0;k<b.length;k++)a(b[k],c);return c.push(")")}if("object"==typeof b){c.push("(");for(k in b)b.hasOwnProperty(k)&&(c.push(k),a(b[k],c));return c.push(")")}return c.push("!n")}return{stringify:function(b){var c=[];a(b,c);return c.join("")}}}(),w=a.ue_qsl||2E3,x=1E3,z=function(){},c=d.JSON&&
d.JSON.stringify||h&&h.stringify,q=e.stringify,b=a.ue||{},e=a.uet||z;(a.uet||z)("bb","ue_frst_v2",{wb:1});var F="//"+a.ue_furl+"/1/batch/1/OE/",E=[],f=[],B=[],A=!1,y,M,N=void 0===a.ue_hpfi?1E3:a.ue_hpfi,H=void 0===a.ue_lpfi?1E4:a.ue_lpfi,G={"scheduled-delivery":1},K=0,L=function(){function u(){if(d.XDomainRequest){var a=new XDomainRequest;a.onerror=z;a.ontimeout=z;a.onprogress=z;a.onload=z;a.timeout=0;return a}if(d.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(d.ActiveXObject){for(var b=
0;b<p.length&&!a;b++)try{a=new ActiveXObject(p[b]),p=[p[b]]}catch(c){}return a}}function J(c){for(var u=[],p=c[0]||{},C=0;C<c.length;C++){var J={};J[c[C].c]=c[C].d;u.push(J)}return{rid:p.r||b.rid,sid:p.s||a.ue_sid,mid:p.m||a.ue_mid,mkt:p.mkt||a.ue_mkt,sn:p.sn||a.ue_sn,reqs:u}}var p="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)&&a[b].length){var p=J(a[b]),C=u();
if(!C)throw"";C.open("POST",F,!0);C.setRequestHeader&&C.setRequestHeader("Content-type","text/plain");C.send(c(p))}},buildPOSTBodyLog:J,isSupported:!0}}(),I=function(){return{send:function(u){for(var J in u)if(u.hasOwnProperty(J)){for(var p=u[J],k=p,f={},d=void 0,C=0;C<k.length;C++)d=k[C].c,f[d]||(f[d]=[]),f[d].push(k[C]);var p=p[0]||{},k=p.sn||a.ue_sn,p=F+(p.m||a.ue_mid)+":"+(p.s||a.ue_sid)+":"+(p.r||b.rid)+(k?":"+k:""),k=[],d=p,C=[],h=void 0;for(h in f)if(f.hasOwnProperty(h))for(var e=0;e<f[h].length;e++){var g=
f[h][e],n=encodeURIComponent((g.cs?q:c)(g.d));C.push({l:n,t:g.t,p:1,c:h,d:g.cs?"c":"j"})}f=C;C=void 0;h="$";for(g=0;g<f.length;){e=f[g];C!=e.c?(d+=h+e.c+"=",h="&",C=e.c):d+=",";var n=d,l=e.d+":",x=e,d=(x.l.match(".{1,"+(w-d.length)+"}[^%]{0,2}")||[])[0]||"";x.l=x.l.substr(d.length);d=n+(l+d+":"+e.t);if(e.l)d+=":"+e.p++ +"_",k.push(d),d=p,h="$",C=0;else if(g++,1!=e.p)for(d+=":"+e.p+"_"+e.p,n=0;n<e.p-1;n++)k[k.length-n-1]+=e.p}k.push(d);p=k;for(k=0;k<p.length;k++)(new Image).src=p[k]}},isSupported:!0}}(),
O=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var p=L.buildPOSTBodyLog(a[b]);if(!navigator.sendBeacon(F,c(p)))throw"";}},isSupported:!!navigator.sendBeacon}}();b._fic=I;b._fac=L;b._fbc=O;b._flq=E;b.sid=b.sid||a.ue_sid;b.mid=b.mid||a.ue_mid;b.furl=b.furl||a.ue_furl;b.sn=b.sn||a.ue_sn;b.isBF=function(){var a=d.performance||d.webkitPerformance,c=v.ue_backdetect&&v.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,p=b.bfini;return a&&a.navigation&&2===a.navigation.type||
1<p||!p&&1<c}();try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",z)}catch(P){a.ueLogError(P,{logLevel:"WARN"})}(function(){b.log&&b.log.isStub&&(b.log.replay(function(a,b,c){var k=a[2]||{};k.t=b;k.r=c;k.n=1;t(a[0],a[1],k)}),b.onunload.replay(function(a){f.push(a[0])}),b.onflush.replay(function(a){B.push(a[0])}))})();b.log=t;b.log.reset=function(){K=0};b.onunload=function(a){f.push(a)};b.onflush=function(a){B.push(a)};
b.attach("beforeunload",n);b.attach("pagehide",n);e("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,d){function v(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function m(c,q){if(!c)return{};c.m&&c.m.message&&(c=c.m);var b=q.m||q.message||"",b=c.m&&c.m.message?b+c.m.message:c.m&&c.m.target&&c.m.target.tagName?b+("Error handler invoked by "+c.m.target.tagName+" tag"):c.m?b+c.m:c.message?b+c.message:b+"Unknown error",b={m:b,f:c.f||c.sourceURL||c.fileName||c.filename||c.m&&c.m.target&&c.m.target.src,l:c.l||c.line||c.lineno||c.lineNumber,c:c.c?""+c.c:c.c,s:[],t:a.ue.d(),name:c.name,type:c.type,
csm:h+" "+(c.fromOnError?"onerror":"ueLogError")},g,l,f=0,m=0,t;g=c.stack||(c.err?c.err.stack:"");b.pageURL=q.pageURL||""+(window.location?window.location.href:"")||"missing";b.logLevel=q.logLevel||n;if(l=q.attribution)b.attribution=""+l;a.ue_ld_err&&d.performance&&d.performance.timing&&(l=d.performance.timing,m=window.performance&&window.performance.now&&window.performance.timing?window.performance.now()+window.performance.timing.navigationStart:+new Date,b.ld=0<l.loadEventStart&&(0===l.loadEventEnd||
m<l.loadEventEnd+3));if(g&&g.split)for(b.csm+=" stack",l=g.split("\n");f<l.length&&b.s.length<e;)(g=l[f++])&&b.s.push(v(g));else for(b.csm+=" callee",l=r(c.args||arguments,"callee"),m=f=0;l&&f<e;)t=w,l.skipTrace||(g=l.toString())&&g.substr&&(t=0===m?4*w:t,t=1==m?2*w:t,b.s.push(g.substr(0,t)),m++),l=r(l,"caller"),f++;if(!b.f&&0<b.s.length&&(f=b)&&f.s){var y;g=0<f.s.length?f.s[0]:"";l=1<f.s.length?f.s[1]:"";g&&(y=g.match(z));y&&3==y.length||!l||(y=l.match(x));y&&3==y.length&&(f.f=y[1],f.l=y[2])}return b}
function r(a,q){try{return a[q]}catch(b){}}function g(c,q){if(c){var b=m(c,q);a.ue.log(b,q.channel||t,{nb:1});try{if(!c.fromOnError){var h=d.console,e=d.JSON,f="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(h){if(e&&e.stringify)try{f+=e.stringify(b)}catch(g){f+="no info provided; converting to string failed"}else f+=b.m;"function"===typeof h.error?h.error(f,b):"function"===typeof h.log&&h.log(f,b)}}}catch(w){}}}function l(c,q){if(c&&!(a.ue_err.ec>
a.ue_err.mxe)){a.ue_err.ec++;a.ue_err.ter.push(c);q=q||{};var b=c.logLevel||q.logLevel;q.logLevel=b;q.attribution=c.attribution||q.attribution;b&&b!=n||ue_err.ecf++;g(c,q)}}if(!a.ueLogError||a.ueLogError.isStub){var t=a.ue_err_chan||"jserr",n="FATAL",h="v5",e=20,w=256,x=/\(?([^\s]*):(\d+):\d+\)?/,z=/.*@(.*):(\d*)/;g.skipTrace=1;m.skipTrace=1;l.skipTrace=1;(function(){if(a.ue_err.erl){var c=a.ue_err.erl.length,q,b;for(q=0;q<c;q++)b=a.ue_err.erl[q],g(b.ex,b.info);ue_err.erl=[]}})();a.ueLogError=l}})(ue_csm,
window);
(function(a,d){a.ue_cel||(a.ue_cel=function(){function v(a,q){q?q.r=x:q={r:x,c:1};q.clog&&h.clog?h.clog(a,q.ns||t,q):q.glog&&h.glog?h.glog(a,q.ns||t,q):h.log(a,q.ns||t,q)}function m(){var a=g.length;if(0<a){for(var q=[],b=0;b<a;b++){var d=g[b].api;d.ready()?(d.on({ts:h.d,ns:t}),l.push(g[b]),v({k:"mso",n:g[b].name,t:h.d()})):q.push(g[b])}g=q}}function r(){if(!r.executed){for(var a=0;a<l.length;a++)l[a].api.off&&l[a].api.off({ts:h.d,ns:t});v({k:"eod",t0:h.t0,t:h.d()},{c:1});r.executed=1;for(a=0;a<l.length;a++)g.push(l[a]);
l=[];clearTimeout(n)}}var g=[],l=[],t=a.ue_cel_ns||"cel",n,h=a.ue,e=a.uet,w=a.uex,x=h.rid,z=d.requestAnimationFrame||function(a){a()};if(h.isBF)v({k:"bft",t:h.d()});else return"function"==typeof e&&e("bb","csmCELLSframework",{wb:1}),setTimeout(m,0),h.onunload(r),n=setTimeout(r,6E5),"function"==typeof w&&w("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,q){g.push({name:a,api:q});v({k:"mrg",n:a,t:h.d()});m()},reset:function(a){v({k:"rst",t0:h.t0,t:h.d()});g=g.concat(l);l=[];for(var q=g.length,
b=0;b<q;b++)g[b].api.off(),g[b].api.reset();x=a||h.rid;m();clearTimeout(n);n=setTimeout(r,6E5);r.executed=0},timeout:function(a,q){return d.setTimeout(function(){z(a)},q)},log:v}}())})(ue_csm,window);
(function(a,d,v){a.ue_pdm||ue.isBF||(a.ue_pdm=function(){function m(){var b={w:l.width,aw:l.availWidth,h:l.height,ah:l.availHeight,cd:l.colorDepth,pd:l.pixelDepth},c={w:v.body.scrollWidth,h:v.body.scrollHeight};e&&e.w==b.w&&e.h==b.h&&e.aw==b.aw&&e.ah==b.ah&&e.pd==b.pd&&e.cd==b.cd||(e=b,e.t=n(),e.k="sci",z(e));w&&w.w==c.w&&w.h==c.h||(w=c,w.t=n(),w.k="doi",z(w));t=a.ue_cel.timeout(m,h)}function r(){z({k:"ebl",t:n()},{ff:1==d.ue_eblfl})}function g(){z({k:"efo",t:n()})}var l,t,n,h,e,w,x=a.ue,z=a.ue_cel.log,
c=a.uet,q=a.uex;"function"==typeof c&&c("bb","csmCELLSpdm",{wb:1});return{on:function(b){h=b.timespan||500;n=b.ts;l=d.screen;x.attach&&(x.attach("blur",r,d),x.attach("focus",g,d));b=d.location;z({k:"pmd",o:b.origin,p:b.pathname,t:n()});a.ue_cel.timeout(m,0);"function"==typeof q&&q("ld","csmCELLSpdm",{wb:1})},off:function(a){clearTimeout(t);x.detach&&(x.detach("blur",r,d),x.detach("focus",g,d));x.count&&(x.count("cel.PDM.TotalExecutions",0),x.count("cel.PDM.TotalExecutionTime",0),x.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return v.body&&a.ue_cel&&a.ue_cel.log},reset:function(){e=w=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,d){a.ue_vpm||ue.isBF||(a.ue_vpm=function(){function v(){var a=t(),c={w:d.innerWidth,h:d.innerHeight,x:d.pageXOffset,y:d.pageYOffset};r&&r.w==c.w&&r.h==c.h&&r.x==c.x&&r.y==c.y||(c.t=a,c.k="vpi",r=c,w(r,{clog:1}));g=0;n=t()-a;h+=1}function m(){g||(g=a.ue_cel.timeout(v,l))}var r,g,l,t,n=0,h=0,e=a.ue,w=a.ue_cel.log,x=a.uet,z=a.uex,c=e.attach,q=e.detach;"function"==typeof x&&x("bb","csmCELLSvpm",{wb:1});return{on:function(b){t=b.ts;l=b.timespan||100;a.ue_cel.timeout(v,0);c&&(c("scroll",m),
c("resize",m));"function"==typeof z&&z("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(g);q&&(q("scroll",m),q("resize",m));e.count&&(e.count("cel.VPI.TotalExecutions",h),e.count("cel.VPI.TotalExecutionTime",n),e.count("cel.VPI.AverageExecutionTime",n/h))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){r=void 0},getVpi:function(){return r}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,d,v){var m=a.ue||{};!m.isBF&&!a.ue_fem&&v.querySelector&&d.getComputedStyle&&[].forEach&&(a.ue_fem=a.ue_bwd?function(){function r(a,b){return a>b?3>a-b:3>b-a}function g(a,b,c){var k;a:{try{if(a){var u=a.getBoundingClientRect();k={x:u.left+c.x|0,y:u.top+c.y|0,w:u.width|0,h:u.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else k=void 0;break a}catch(p){}k=void 0}if(k&&!a.cel_b)a.cel_b=k,E({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi",cl:a.className},
{clog:1});else{if(c=k)c=a.cel_b,u=k,c=u.d===c.d&&1===u.d?!1:!(r(c.x,u.x)&&r(c.y,u.y)&&r(c.w,u.w)&&r(c.h,u.h)&&c.d===u.d);c&&(a.cel_b=k,E({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi"},{clog:1}))}}function l(a,b,c){var k;k=a.c?v.getElementsByClassName(a.c):a.id?[v.getElementById(a.id)]:v.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<k.length;widgetIndex++){var u=k[widgetIndex];u&&(u.cel_n||(u.cel_n=u.getAttribute("cel_widget_id")||(a.id_gen||F)(u,widgetIndex)||
u.id),a.w.push(u),h(p,u,b,c))}}function t(a,b){f.contains(a)||E({n:a.cel_n,t:b,k:"ewd"},{clog:1})}function n(a){I.length&&ue_cel.timeout(function(){for(var b=U(),u=!1;U()-b<c&&!u;){for(u=P;0<u--&&0<I.length;){var p=I.shift();k[p.type](p.elem,p.time,p.pageOffset)}u=0===I.length}O++;n(a)},0)}function h(a,b,c,k){I.push({type:a,elem:b,time:c,pageOffset:k})}function e(a,c,k){for(var u=0;u<b.length;u++)for(var p=b[u].w||[],J=0;J<p.length;J++)h(a,p[J],c,k)}function w(){L||(L=a.ue_cel.timeout(function(){L=
null;var a={x:d.pageXOffset,y:d.pageYOffset},c=q();e(u,c);for(var k=0;k<b.length;k++)h(J,b[k],c,a);n(c)},z))}function x(){L||K||(K=a.ue_cel.timeout(function(){K=null;var a={x:d.pageXOffset,y:d.pageYOffset},b=q();e(p,b,a);n(b)},z))}var z=50,c=4.5,q,b=[],F=function(){},E=a.ue_cel.log,f,B,A,y,M=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!M,H,G,K,L,I=[],O=0,P=null,u="removedWidget",J="updateWidgets",p="processWidget",k,R=d.performance||{},U=R.now&&function(){return R.now()}||
function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(c){function u(){if(A&&y&&f&&f.contains&&f.getBoundingClientRect&&q){k={removedWidget:t,updateWidgets:l,processWidget:g};if(N){var a={attributes:!0,subtree:!0};H=new M(x);G=new M(w);H.observe(f,a);G.observe(f,{childList:!0,subtree:!0});G.observe(B,a)}else A.call(f,"DOMAttrModified",x),A.call(f,"DOMNodeInserted",w),A.call(f,"DOMNodeRemoved",w),A.call(B,"DOMNodeInserted",x),A.call(B,"DOMNodeRemoved",
x);w()}}f=v.body;B=v.head;A=f.addEventListener;y=f.removeEventListener;q=c.ts;b=a.cel_widgets||[];P=c.bs||5;m.deffered?u():m.attach&&m.attach("load",u);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){A&&y&&f&&f.contains&&f.getBoundingClientRect&&q&&(G&&(G.disconnect(),G=null),H&&(H.disconnect(),H=null),y.call(f,"DOMAttrModified",x),y.call(f,"DOMNodeInserted",w),y.call(f,"DOMNodeRemoved",w),y.call(B,"DOMNodeInserted",x),y.call(B,"DOMNodeRemoved",x));m.count&&m.count("cel.widgets.batchesProcessed",
O)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){b=a.cel_widgets||[]}}}():function(){function r(){a.ue_cel.timeout(function(){F.splice(0).forEach(function(a){E(a,{clog:1})})},0)}function g(a){for(var b={x:d.pageXOffset,y:d.pageYOffset},c=0;c<q.length;c++){var J=q[c];if(J.w&&J.w.length)for(var p=0;p<J.w.length;p++){var k=J.w[p],f;a:{try{var h=k,C=b;if(h){var e=h.getBoundingClientRect();f={x:e.left+C.x|0,y:e.top+C.y|0,w:e.width|0,h:e.height|0,d:(0===h.offsetWidth&&0===h.offsetHeight)|
0}}else f=void 0;break a}catch(g){}f=void 0}if(f&&!k.cel_b)k.cel_b=f,F.push({n:k.cel_n,w:k.cel_b.w,h:k.cel_b.h,d:k.cel_b.d,x:k.cel_b.x,y:k.cel_b.y,t:a,k:"ewi",cl:k.className});else{if(h=f)h=k.cel_b,C=f,h=C.d===h.d&&1===C.d?!1:!(t(h.x,C.x)&&t(h.y,C.y)&&t(h.w,C.w)&&t(h.h,C.h)&&h.d===C.d);h&&(k.cel_b=f,F.push({n:k.cel_n,w:k.cel_b.w,h:k.cel_b.h,d:k.cel_b.d,x:k.cel_b.x,y:k.cel_b.y,t:a,k:"ewi"}))}}}}function l(a){for(var c=0;c<q.length;c++){var u=q[c],J;J=u;J=J.c?v.getElementsByClassName(J.c):J.id?[v.getElementById(J.id)]:
v.querySelectorAll(J.s);var p=u.w||[],k;for(k=0;k<p.length;k++){var d=p[k];f.contains(d)||F.push({n:d.cel_n,t:a,k:"ewd"})}u.w=[];for(k=0;k<J.length;k++)if(p=J[k])p.cel_n||(p.cel_n=p.getAttribute("cel_widget_id")||(u.id_gen||b)(p,k)||p.id),u.w.push(p)}h()}function t(a,b){return a>b?3>a-b:3>b-a}function n(){L||(L=a.ue_cel.timeout(function(){L=null;e("dwe",l);r()},w))}function h(){L||K||(K=a.ue_cel.timeout(function(){K=null;e("dwpc",g);r()},w))}function e(a,b){var u=c();b(u);var J=c(),u=J-u;u<=x?J=0:
J-I>=z?(I=J,J=0):(ue_fem.off(),J=1);(F.length||J)&&F.push({k:"ewt",e:a,d:u,ex:J,t:c()})}var w=50,x=10,z=3E3,c,q=[],b=function(){},F=[],E=a.ue_cel.log,f,B,A,y,M=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!M,H,G,K,L,I=-z;"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(b){function d(){if(A&&y&&f&&f.contains&&f.getBoundingClientRect&&c){if(N){var a={attributes:!0,subtree:!0};H=new M(h);G=new M(n);H.observe(f,a);G.observe(f,{childList:!0,subtree:!0});
G.observe(B,a)}else A.call(f,"DOMAttrModified",h),A.call(f,"DOMNodeInserted",n),A.call(f,"DOMNodeRemoved",n),A.call(B,"DOMNodeInserted",h),A.call(B,"DOMNodeRemoved",h);n()}}f=v.body;B=v.head;A=f.addEventListener;y=f.removeEventListener;c=b.ts;q=a.cel_widgets||[];m.deffered?d():m.attach&&m.attach("load",d);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){A&&y&&f&&f.contains&&f.getBoundingClientRect&&c&&(G&&(G.disconnect(),G=null),H&&(H.disconnect(),H=null),y.call(f,"DOMAttrModified",
h),y.call(f,"DOMNodeInserted",n),y.call(f,"DOMNodeRemoved",n),y.call(B,"DOMNodeInserted",h),y.call(B,"DOMNodeRemoved",h))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){q=a.cel_widgets||[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))})(ue_csm,window,document);
(function(a,d){a.ue_mcm||a.ue.isBF||(a.ue_mcm=function(){function v(a){if(a.id)return"//*[@id='"+a.id+"']";var d;d=1;var g;for(g=a.previousSibling;g;g=g.previousSibling)g.nodeName==a.nodeName&&(d+=1);g=a.nodeName;1!=d&&(g+="["+d+"]");a.parentNode&&(g=v(a.parentNode)+"/"+g);return g}function m(a){var e=a.srcElement||a.target||{},w={k:r,w:d.body.scrollWidth,h:d.body.scrollHeight,t:g(),x:a.pageX,y:a.pageY,p:v(e),n:e.nodeName,e:n};a.button&&(w.b=a.button);e.href&&(w.r=e.href);e.id&&(w.i=e.id);e.className&&
(w.c=e.className.split(/\s+/));t(w,{c:1})}var r="mcm",g,l=a.ue,t=a.ue_cel.log,n=a.ue_mce||"click";return{on:function(a){g=a.ts;l.attach&&l.attach(n,m,d)},off:function(a){l.detach&&l.detach(n,m,d)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){}}}(),a.ue_cel&&a.ue_cel.registerModule("mouse click module",a.ue_mcm))})(ue_csm,document);
(function(a,d){a.ue_mmm||a.ue.isBF||(a.ue_mmm=function(v){function m(a,b){var c={x:a.pageX||a.x||0,y:a.pageY||a.y||0,t:h()};!b&&M&&(c.t-M.t<l||c.x==M.x&&c.y==M.y)||(M=c,B.push(c))}function r(){if(B.length){E=K.now();for(var a=0;a<B.length;a++){var d=B[a],h=a;N=B[y];H=d;var e=void 0;if(!(e=2>h)){a:if(B[h].t-B[h-1].t>g)e=0;else{for(e=y+1;e<h;e++){var u=N,J=H,p=B[e];G=(J.x-u.x)*(u.y-p.y)-(u.x-p.x)*(J.y-u.y);if(G*G/((J.x-u.x)*(J.x-u.x)+(J.y-u.y)*(J.y-u.y))>t){e=0;break a}}e=1}e=!e}e?y=h-1:A.pop();A.push(d)}f=
K.now()-E;c=Math.min(c,f);q=Math.max(q,f);b=(b*F+f)/(F+1);F+=1;x({k:n,e:A,min:Math.floor(1E3*c),max:Math.floor(1E3*q),avg:Math.floor(1E3*b)},{c:1});B=[];A=[];y=0}}var g=100,l=20,t=25,n="mmm1",h,e,w=a.ue,x=a.ue_cel.log,z,c=1E3,q=0,b=0,F=0,E,f,B=[],A=[],y=0,M,N,H,G,K=v&&v.now&&v||Date.now&&Date||{now:function(){return(new Date).getTime()}};return{on:function(a){h=a.ts;e=a.ns;w.attach&&w.attach("mousemove",m,d);z=setInterval(r,3E3)},off:function(a){e&&(M&&m(M,!0),r());clearInterval(z);w.detach&&w.detach("mousemove",
m,d)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){B=[];A=[];y=0;M=null}}}(window.performance),a.ue_cel&&a.ue_cel.registerModule("mouse move module",a.ue_mmm))})(ue_csm,document);