(function(b,e,v){function n(a){for(var c={},b,f,r=0;r<a.length;r++)f=a[r],b=f.r+f.s+f.m,f.c&&(c[b]||(c[b]=[]),c[b].push(a[r]));return c}function d(a){for(var c=1;c<arguments.length;c++){var b=arguments[c];try{if(b.isSupported)return b.send(a)}catch(f){}}}function l(){for(var a=0;a<B.length;a++)B[a]();k.length&&d(n(k.splice(0,k.length)),N,K,I);A=L=0}function p(c,O,t){t=t||{};0===t.bf&&a.isBF||(c={r:t.r||a.rid,s:t.s||b.ue_sid,m:t.m||b.ue_mid,mkt:t.mkt||b.ue_mkt,sn:t.sn||b.ue_sn,c:O,d:c,t:t.t||a.d(),
cs:t.c&&b.ue_qsl},t.b?d(n([c]),N,I):t.nb?d(n([c]),N,K,I):t.img||G[O]?d(n([c]),I):t.n?(k.push(c),0===M?l():A||(A=e.setTimeout(l,M))):(k.push(c),L||(L=e.setTimeout(l,H))))}function u(a,c,b){J++;J==x?p({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},e.ue_err_chan||"jserr"):J<x&&p(a,c,b)}function q(){if(!C){for(var a=0;a<g.length;a++)g[a]();for(a=0;a<B.length;a++)B[a]();d(n(k.splice(0,k.length)),N,I);C=!0}}var h={};(function(){function a(c){return 10>c?"0"+c:c}function c(a){f.lastIndex=
0;return f.test(a)?'"'+a.replace(f,function(a){var c=F[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(a,w){var f,F,d,h,k=r,E,D=w[a];D&&"object"===typeof D&&"function"===typeof D.toJSON&&(D=D.toJSON(a));"function"===typeof e&&(D=e.call(w,a,D));switch(typeof D){case "string":return c(D);case "number":return isFinite(D)?String(D):"null";case "boolean":case "null":return String(D);case "object":if(!D)return"null";r+=g;E=[];if("[object Array]"===
Object.prototype.toString.apply(D)){h=D.length;for(f=0;f<h;f+=1)E[f]=b(f,D)||"null";d=0===E.length?"[]":r?"[\n"+r+E.join(",\n"+r)+"\n"+k+"]":"["+E.join(",")+"]";r=k;return d}if(e&&"object"===typeof e)for(h=e.length,f=0;f<h;f+=1)"string"===typeof e[f]&&(F=e[f],(d=b(F,D))&&E.push(c(F)+(r?": ":":")+d));else for(F in D)Object.prototype.hasOwnProperty.call(D,F)&&(d=b(F,D))&&E.push(c(F)+(r?": ":":")+d);d=0===E.length?"{}":r?"{\n"+r+E.join(",\n"+r)+"\n"+k+"}":"{"+E.join(",")+"}";r=k;return d}}"function"!==
typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(c){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
r,g,F={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},e;"function"!==typeof h.stringify&&(h.stringify=function(a,c,w){var f;g=r="";if("number"===typeof w)for(f=0;f<w;f+=1)g+=" ";else"string"===typeof w&&(g=w);if((e=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return b("",{"":a})})})();var m=function(){function a(c,b){if(null==c)return b.push("!n");if("number"===typeof c)return b.push("!"+c);if("string"===
typeof c)return"\\"==c[c.length-1]?b.push("'"+c.replace(/'/g,"\\'")+"u005C'"):b.push("'"+c.replace(/'/g,"\\'")+"'");if("boolean"===typeof c)return b.push(c?"!t":"!f");if(c instanceof Array){b.push("*");for(var f=0;f<c.length;f++)a(c[f],b);return b.push(")")}if("object"==typeof c){b.push("(");for(f in c)c.hasOwnProperty(f)&&(b.push(f),a(c[f],b));return b.push(")")}return b.push("!n")}return{stringify:function(c){var b=[];a(c,b);return b.join("")}}}(),y=b.ue_qsl||2E3,x=1E3,z=function(){},c=e.JSON&&
e.JSON.stringify||h&&h.stringify,r=m.stringify,a=b.ue||{},m=b.uet||z;(b.uet||z)("bb","ue_frst_v2",{wb:1});var E="//"+b.ue_furl+"/1/batch/1/OE/",k=[],g=[],B=[],C=!1,A,L,M=void 0===b.ue_hpfi?1E3:b.ue_hpfi,H=void 0===b.ue_lpfi?1E4:b.ue_lpfi,G={"scheduled-delivery":1},J=0,K=function(){function w(){if(e.XDomainRequest){var a=new XDomainRequest;a.onerror=z;a.ontimeout=z;a.onprogress=z;a.onload=z;a.timeout=0;return a}if(e.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(e.ActiveXObject){for(var c=
0;c<t.length&&!a;c++)try{a=new ActiveXObject(t[c]),t=[t[c]]}catch(b){}return a}}function r(c){for(var w=[],t=c[0]||{},F=0;F<c.length;F++){var O={};O[c[F].c]=c[F].d;w.push(O)}return{rid:t.r||a.rid,sid:t.s||b.ue_sid,mid:t.m||b.ue_mid,mkt:t.mkt||b.ue_mkt,sn:t.sn||b.ue_sn,reqs:w}}var t="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)&&a[b].length){var t=r(a[b]),F=w();
if(!F)throw"";F.open("POST",E,!0);F.setRequestHeader&&F.setRequestHeader("Content-type","text/plain");F.send(c(t))}},buildPOSTBodyLog:r,isSupported:!0}}(),I=function(){return{send:function(w){for(var O in w)if(w.hasOwnProperty(O)){for(var t=w[O],f=t,g={},e=void 0,F=0;F<f.length;F++)e=f[F].c,g[e]||(g[e]=[]),g[e].push(f[F]);var t=t[0]||{},f=t.sn||b.ue_sn,t=E+(t.m||b.ue_mid)+":"+(t.s||b.ue_sid)+":"+(t.r||a.rid)+(f?":"+f:""),f=[],e=t,F=[],d=void 0;for(d in g)if(g.hasOwnProperty(d))for(var h=0;h<g[d].length;h++){var k=
g[d][h],m=encodeURIComponent((k.cs?r:c)(k.d));F.push({l:m,t:k.t,p:1,c:d,d:k.cs?"c":"j"})}g=F;F=void 0;d="$";for(k=0;k<g.length;){h=g[k];F!=h.c?(e+=d+h.c+"=",d="&",F=h.c):e+=",";var m=e,l=h.d+":",q=h,e=(q.l.match(".{1,"+(y-e.length)+"}[^%]{0,2}")||[])[0]||"";q.l=q.l.substr(e.length);e=m+(l+e+":"+h.t);if(h.l)e+=":"+h.p++ +"_",f.push(e),e=t,d="$",F=0;else if(k++,1!=h.p)for(e+=":"+h.p+"_"+h.p,m=0;m<h.p-1;m++)f[f.length-m-1]+=h.p}f.push(e);t=f;for(f=0;f<t.length;f++)(new Image).src=t[f]}},isSupported:!0}}(),
N=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var t=K.buildPOSTBodyLog(a[b]);if(!navigator.sendBeacon(E,c(t)))throw"";}},isSupported:!!navigator.sendBeacon}}();a._fic=I;a._fac=K;a._fbc=N;a._flq=k;a.sid=a.sid||b.ue_sid;a.mid=a.mid||b.ue_mid;a.furl=a.furl||b.ue_furl;a.sn=a.sn||b.ue_sn;a.isBF=function(){var c=e.performance||e.webkitPerformance,b=v.ue_backdetect&&v.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,t=a.bfini;return c&&c.navigation&&2===c.navigation.type||
1<t||!t&&1<b}();try{e.amznJQ&&e.amznJQ.declareAvailable&&e.amznJQ.declareAvailable("forester-client"),e.P&&e.P.register&&e.P.register("forester-client",z)}catch(P){b.ueLogError(P,{logLevel:"WARN"})}(function(){a.log&&a.log.isStub&&(a.log.replay(function(a,c,b){var f=a[2]||{};f.t=c;f.r=b;f.n=1;u(a[0],a[1],f)}),a.onunload.replay(function(a){g.push(a[0])}),a.onflush.replay(function(a){B.push(a[0])}))})();a.log=u;a.log.reset=function(){J=0};a.onunload=function(a){g.push(a)};a.onflush=function(a){B.push(a)};
a.attach("beforeunload",q);a.attach("pagehide",q);m("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(b,e){function v(c){if(c)return c.replace(/^\s+|\s+$/g,"")}function n(c,r){if(!c)return{};c.m&&c.m.message&&(c=c.m);var a=r.m||r.message||"",a=c.m&&c.m.message?a+c.m.message:c.m&&c.m.target&&c.m.target.tagName?a+("Error handler invoked by "+c.m.target.tagName+" tag"):c.m?a+c.m:c.message?a+c.message:a+"Unknown error",a={m:a,f:c.f||c.sourceURL||c.fileName||c.filename||c.m&&c.m.target&&c.m.target.src,l:c.l||c.line||c.lineno||c.lineNumber,c:c.c?""+c.c:c.c,s:[],t:b.ue.d(),name:c.name,type:c.type,
csm:h+" "+(c.fromOnError?"onerror":"ueLogError")},E,k,g=0,l=0,p;E=c.stack||(c.err?c.err.stack:"");a.pageURL=r.pageURL||""+(window.location?window.location.href:"")||"missing";a.logLevel=r.logLevel||q;if(k=r.attribution)a.attribution=""+k;b.ue_ld_err&&e.performance&&e.performance.timing&&(k=e.performance.timing,l=window.performance&&window.performance.now&&window.performance.timing?window.performance.now()+window.performance.timing.navigationStart:+new Date,a.ld=0<k.loadEventStart&&(0===k.loadEventEnd||
l<k.loadEventEnd+3));if(E&&E.split)for(a.csm+=" stack",k=E.split("\n");g<k.length&&a.s.length<m;)(E=k[g++])&&a.s.push(v(E));else for(a.csm+=" callee",k=d(c.args||arguments,"callee"),l=g=0;k&&g<m;)p=y,k.skipTrace||(E=k.toString())&&E.substr&&(p=0===l?4*y:p,p=1==l?2*y:p,a.s.push(E.substr(0,p)),l++),k=d(k,"caller"),g++;if(!a.f&&0<a.s.length&&(g=a)&&g.s){var n;E=0<g.s.length?g.s[0]:"";k=1<g.s.length?g.s[1]:"";E&&(n=E.match(z));n&&3==n.length||!k||(n=k.match(x));n&&3==n.length&&(g.f=n[1],g.l=n[2])}return a}
function d(c,b){try{return c[b]}catch(a){}}function l(c,r){if(c){var a=n(c,r);b.ue.log(a,r.channel||u,{nb:1});try{if(!c.fromOnError){var d=e.console,h=e.JSON,g="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(d){if(h&&h.stringify)try{g+=h.stringify(a)}catch(m){g+="no info provided; converting to string failed"}else g+=a.m;"function"===typeof d.error?d.error(g,a):"function"===typeof d.log&&d.log(g,a)}}}catch(l){}}}function p(c,r){if(c&&!(b.ue_err.ec>
b.ue_err.mxe)){b.ue_err.ec++;b.ue_err.ter.push(c);r=r||{};var a=c.logLevel||r.logLevel;r.logLevel=a;r.attribution=c.attribution||r.attribution;a&&a!=q||ue_err.ecf++;l(c,r)}}if(!b.ueLogError||b.ueLogError.isStub){var u=b.ue_err_chan||"jserr",q="FATAL",h="v5",m=20,y=256,x=/\(?([^\s]*):(\d+):\d+\)?/,z=/.*@(.*):(\d*)/;l.skipTrace=1;n.skipTrace=1;p.skipTrace=1;(function(){if(b.ue_err.erl){var c=b.ue_err.erl.length,r,a;for(r=0;r<c;r++)a=b.ue_err.erl[r],l(a.ex,a.info);ue_err.erl=[]}})();b.ueLogError=p}})(ue_csm,
window);
(function(b,e){b.ue_cel||(b.ue_cel=function(){function v(c,b){b?b.r=x:b={r:x,c:1};b.clog&&h.clog?h.clog(c,b.ns||u,b):b.glog&&h.glog?h.glog(c,b.ns||u,b):h.log(c,b.ns||u,b)}function n(){var c=l.length;if(0<c){for(var b=[],a=0;a<c;a++){var e=l[a].api;e.ready()?(e.on({ts:h.d,ns:u}),p.push(l[a]),v({k:"mso",n:l[a].name,t:h.d()})):b.push(l[a])}l=b}}function d(){if(!d.executed){for(var c=0;c<p.length;c++)p[c].api.off&&p[c].api.off({ts:h.d,ns:u});v({k:"eod",t0:h.t0,t:h.d()},{c:1});d.executed=1;for(c=0;c<p.length;c++)l.push(p[c]);
p=[];clearTimeout(q)}}var l=[],p=[],u=b.ue_cel_ns||"cel",q,h=b.ue,m=b.uet,y=b.uex,x=h.rid,z=e.requestAnimationFrame||function(c){c()};if(h.isBF)v({k:"bft",t:h.d()});else return"function"==typeof m&&m("bb","csmCELLSframework",{wb:1}),setTimeout(n,0),h.onunload(d),q=setTimeout(d,6E5),"function"==typeof y&&y("ld","csmCELLSframework",{wb:1}),{registerModule:function(c,b){l.push({name:c,api:b});v({k:"mrg",n:c,t:h.d()});n()},reset:function(c){v({k:"rst",t0:h.t0,t:h.d()});l=l.concat(p);p=[];for(var b=l.length,
a=0;a<b;a++)l[a].api.off(),l[a].api.reset();x=c||h.rid;n();clearTimeout(q);q=setTimeout(d,6E5);d.executed=0},timeout:function(c,b){return e.setTimeout(function(){z(c)},b)},log:v}}())})(ue_csm,window);
(function(b,e,v){b.ue_pdm||ue.isBF||(b.ue_pdm=function(){function n(){var a={w:p.width,aw:p.availWidth,h:p.height,ah:p.availHeight,cd:p.colorDepth,pd:p.pixelDepth},c={w:v.body.scrollWidth,h:v.body.scrollHeight};m&&m.w==a.w&&m.h==a.h&&m.aw==a.aw&&m.ah==a.ah&&m.pd==a.pd&&m.cd==a.cd||(m=a,m.t=q(),m.k="sci",z(m));y&&y.w==c.w&&y.h==c.h||(y=c,y.t=q(),y.k="doi",z(y));u=b.ue_cel.timeout(n,h)}function d(){z({k:"ebl",t:q()})}function l(){z({k:"efo",t:q()})}var p,u,q,h,m,y,x=b.ue,z=b.ue_cel.log,c=b.uet,r=b.uex;
"function"==typeof c&&c("bb","csmCELLSpdm",{wb:1});return{on:function(a){h=a.timespan||500;q=a.ts;p=e.screen;x.attach&&(x.attach("blur",d,e),x.attach("focus",l,e));a=e.location;z({k:"pmd",o:a.origin,p:a.pathname,t:q()});b.ue_cel.timeout(n,0);"function"==typeof r&&r("ld","csmCELLSpdm",{wb:1})},off:function(a){clearTimeout(u);x.detach&&(x.detach("blur",d,e),x.detach("focus",l,e));x.count&&(x.count("cel.PDM.TotalExecutions",0),x.count("cel.PDM.TotalExecutionTime",0),x.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return v.body&&b.ue_cel&&b.ue_cel.log},reset:function(){m=y=null}}}(),b.ue_cel&&b.ue_cel.registerModule("page module",b.ue_pdm))})(ue_csm,window,document);
(function(b,e){b.ue_vpm||ue.isBF||(b.ue_vpm=function(){function v(){var a=u(),c={w:e.innerWidth,h:e.innerHeight,x:e.pageXOffset,y:e.pageYOffset};d&&d.w==c.w&&d.h==c.h&&d.x==c.x&&d.y==c.y||(c.t=a,c.k="vpi",d=c,y(d,{clog:1}));l=0;q=u()-a;h+=1}function n(){l||(l=b.ue_cel.timeout(v,p))}var d,l,p,u,q=0,h=0,m=b.ue,y=b.ue_cel.log,x=b.uet,z=b.uex,c=m.attach,r=m.detach;"function"==typeof x&&x("bb","csmCELLSvpm",{wb:1});return{on:function(a){u=a.ts;p=a.timespan||100;b.ue_cel.timeout(v,0);c&&(c("scroll",n),
c("resize",n));"function"==typeof z&&z("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(l);r&&(r("scroll",n),r("resize",n));m.count&&(m.count("cel.VPI.TotalExecutions",h),m.count("cel.VPI.TotalExecutionTime",q),m.count("cel.VPI.AverageExecutionTime",q/h))},ready:function(){return b.ue_cel&&b.ue_cel.log},reset:function(){d=void 0},getVpi:function(){return d}}}(),b.ue_cel&&b.ue_cel.registerModule("viewport module",b.ue_vpm))})(ue_csm,window);
(function(b,e,v){var n=b.ue||{};!n.isBF&&!b.ue_fem&&v.querySelector&&e.getComputedStyle&&[].forEach&&(b.ue_fem=b.ue_bwd?function(){function d(a,c){return a>c?3>a-c:3>c-a}function l(a,c,b){var w;a:{try{if(a){var f=a.getBoundingClientRect();w={x:f.left+b.x|0,y:f.top+b.y|0,w:f.width|0,h:f.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else w=void 0;break a}catch(t){}w=void 0}if(w&&!a.cel_b)a.cel_b=w,k({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:c,k:"ewi",cl:a.className},
{clog:1});else{if(b=w)b=a.cel_b,f=w,b=f.d===b.d&&1===f.d?!1:!(d(b.x,f.x)&&d(b.y,f.y)&&d(b.w,f.w)&&d(b.h,f.h)&&b.d===f.d);b&&(a.cel_b=w,k({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:c,k:"ewi"},{clog:1}))}}function p(a,c,b){var w;w=a.c?v.getElementsByClassName(a.c):a.id?[v.getElementById(a.id)]:v.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<w.length;widgetIndex++){var f=w[widgetIndex];f&&(f.cel_n||(f.cel_n=f.getAttribute("cel_widget_id")||(a.id_gen||E)(f,widgetIndex)||
f.id),a.w.push(f),h(t,f,c,b))}}function u(a,c){g.contains(a)||k({n:a.cel_n,t:c,k:"ewd"},{clog:1})}function q(a){I.length&&ue_cel.timeout(function(){for(var b=S(),w=!1;S()-b<c&&!w;){for(w=P;0<w--&&0<I.length;){var t=I.shift();f[t.type](t.elem,t.time,t.pageOffset)}w=0===I.length}N++;q(a)},0)}function h(a,c,b,w){I.push({type:a,elem:c,time:b,pageOffset:w})}function m(c,b,w){for(var f=0;f<a.length;f++)for(var t=a[f].w||[],O=0;O<t.length;O++)h(c,t[O],b,w)}function y(){K||(K=b.ue_cel.timeout(function(){K=
null;var c={x:e.pageXOffset,y:e.pageYOffset},b=r();m(w,b);for(var f=0;f<a.length;f++)h(O,a[f],b,c);q(b)},z))}function x(){K||J||(J=b.ue_cel.timeout(function(){J=null;var a={x:e.pageXOffset,y:e.pageYOffset},c=r();m(t,c,a);q(c)},z))}var z=50,c=4.5,r,a=[],E=function(){},k=b.ue_cel.log,g,B,C,A,L=e.MutationObserver||e.WebKitMutationObserver||e.MozMutationObserver,M=!!L,H,G,J,K,I=[],N=0,P=null,w="removedWidget",O="updateWidgets",t="processWidget",f,Q=e.performance||{},S=Q.now&&function(){return Q.now()}||
function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(c){function w(){if(C&&A&&g&&g.contains&&g.getBoundingClientRect&&r){f={removedWidget:u,updateWidgets:p,processWidget:l};if(M){var a={attributes:!0,subtree:!0};H=new L(x);G=new L(y);H.observe(g,a);G.observe(g,{childList:!0,subtree:!0});G.observe(B,a)}else C.call(g,"DOMAttrModified",x),C.call(g,"DOMNodeInserted",y),C.call(g,"DOMNodeRemoved",y),C.call(B,"DOMNodeInserted",x),C.call(B,"DOMNodeRemoved",
x);y()}}g=v.body;B=v.head;C=g.addEventListener;A=g.removeEventListener;r=c.ts;a=b.cel_widgets||[];P=c.bs||5;n.deffered?w():n.attach&&n.attach("load",w);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){C&&A&&g&&g.contains&&g.getBoundingClientRect&&r&&(G&&(G.disconnect(),G=null),H&&(H.disconnect(),H=null),A.call(g,"DOMAttrModified",x),A.call(g,"DOMNodeInserted",y),A.call(g,"DOMNodeRemoved",y),A.call(B,"DOMNodeInserted",x),A.call(B,"DOMNodeRemoved",x));n.count&&n.count("cel.widgets.batchesProcessed",
N)},ready:function(){return b.ue_cel&&b.ue_cel.log},reset:function(){a=b.cel_widgets||[]}}}():function(){function d(){b.ue_cel.timeout(function(){E.splice(0).forEach(function(a){k(a,{clog:1})})},0)}function l(a){for(var c={x:e.pageXOffset,y:e.pageYOffset},b=0;b<r.length;b++){var O=r[b];if(O.w&&O.w.length)for(var t=0;t<O.w.length;t++){var f=O.w[t],g;a:{try{var d=f,F=c;if(d){var h=d.getBoundingClientRect();g={x:h.left+F.x|0,y:h.top+F.y|0,w:h.width|0,h:h.height|0,d:(0===d.offsetWidth&&0===d.offsetHeight)|
0}}else g=void 0;break a}catch(k){}g=void 0}if(g&&!f.cel_b)f.cel_b=g,E.push({n:f.cel_n,w:f.cel_b.w,h:f.cel_b.h,d:f.cel_b.d,x:f.cel_b.x,y:f.cel_b.y,t:a,k:"ewi",cl:f.className});else{if(d=g)d=f.cel_b,F=g,d=F.d===d.d&&1===F.d?!1:!(u(d.x,F.x)&&u(d.y,F.y)&&u(d.w,F.w)&&u(d.h,F.h)&&d.d===F.d);d&&(f.cel_b=g,E.push({n:f.cel_n,w:f.cel_b.w,h:f.cel_b.h,d:f.cel_b.d,x:f.cel_b.x,y:f.cel_b.y,t:a,k:"ewi"}))}}}}function p(c){for(var b=0;b<r.length;b++){var w=r[b],O;O=w;O=O.c?v.getElementsByClassName(O.c):O.id?[v.getElementById(O.id)]:
v.querySelectorAll(O.s);var t=w.w||[],f;for(f=0;f<t.length;f++){var d=t[f];g.contains(d)||E.push({n:d.cel_n,t:c,k:"ewd"})}w.w=[];for(f=0;f<O.length;f++)if(t=O[f])t.cel_n||(t.cel_n=t.getAttribute("cel_widget_id")||(w.id_gen||a)(t,f)||t.id),w.w.push(t)}h()}function u(a,c){return a>c?3>a-c:3>c-a}function q(){K||(K=b.ue_cel.timeout(function(){K=null;m("dwe",p);d()},y))}function h(){K||J||(J=b.ue_cel.timeout(function(){J=null;m("dwpc",l);d()},y))}function m(a,b){var w=c();b(w);var O=c(),w=O-w;w<=x?O=0:
O-I>=z?(I=O,O=0):(ue_fem.off(),O=1);(E.length||O)&&E.push({k:"ewt",e:a,d:w,ex:O,t:c()})}var y=50,x=10,z=3E3,c,r=[],a=function(){},E=[],k=b.ue_cel.log,g,B,C,A,L=e.MutationObserver||e.WebKitMutationObserver||e.MozMutationObserver,M=!!L,H,G,J,K,I=-z;"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(a){function d(){if(C&&A&&g&&g.contains&&g.getBoundingClientRect&&c){if(M){var a={attributes:!0,subtree:!0};H=new L(h);G=new L(q);H.observe(g,a);G.observe(g,{childList:!0,subtree:!0});
G.observe(B,a)}else C.call(g,"DOMAttrModified",h),C.call(g,"DOMNodeInserted",q),C.call(g,"DOMNodeRemoved",q),C.call(B,"DOMNodeInserted",h),C.call(B,"DOMNodeRemoved",h);q()}}g=v.body;B=v.head;C=g.addEventListener;A=g.removeEventListener;c=a.ts;r=b.cel_widgets||[];n.deffered?d():n.attach&&n.attach("load",d);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){C&&A&&g&&g.contains&&g.getBoundingClientRect&&c&&(G&&(G.disconnect(),G=null),H&&(H.disconnect(),H=null),A.call(g,"DOMAttrModified",
h),A.call(g,"DOMNodeInserted",q),A.call(g,"DOMNodeRemoved",q),A.call(B,"DOMNodeInserted",h),A.call(B,"DOMNodeRemoved",h))},ready:function(){return b.ue_cel&&b.ue_cel.log},reset:function(){r=b.cel_widgets||[]}}}(),b.ue_cel&&b.ue_fem&&b.ue_cel.registerModule("features module",b.ue_fem))})(ue_csm,window,document);